# Generated by Django 6.0.5 on 2026-05-30 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manuals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eicas_message', models.CharField(blank=True, max_length=255)),
                ('fault_code', models.CharField(blank=True, max_length=100)),
                ('mel_number', models.CharField(blank=True, max_length=100)),
                ('fim_chapter', models.CharField(blank=True, max_length=100)),
                ('amm_chapter', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_references', to='manuals.aircraft')),
            ],
            options={
                'ordering': ['aircraft', 'eicas_message', 'fault_code'],
            },
        ),
    ]
