# Generated by Django 6.0.5 on 2026-05-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
        ('manuals', '0002_alter_aircraft_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='dispatchreference',
            unique_together={('aircraft', 'eicas_message', 'fault_code')},
        ),
    ]
