# Generated by Django 6.0.5 on 2026-05-31 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_dispatchreference_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchreference',
            name='amm_search_keyword',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dispatchreference',
            name='fim_search_keyword',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dispatchreference',
            name='mel_search_keyword',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
