# Generated by Django 6.0.5 on 2026-05-31 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_dispatchreference_amm_search_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchreference',
            name='amm_chapter_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchreference',
            name='amm_page_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchreference',
            name='fim_chapter_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchreference',
            name='fim_page_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchreference',
            name='mel_manual_file_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchreference',
            name='mel_page_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
