# Generated by Django 6.0.5 on 2026-05-31 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_dispatchreference_amm_chapter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchreference',
            name='amm_task_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dispatchreference',
            name='fim_task_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dispatchreference',
            name='mel_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
