# Generated by Django 6.0.5 on 2026-05-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0005_dispatchreference_amm_task_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchKeywordDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('related_keywords', models.TextField(blank=True, help_text='쉼표로 구분: PACK, AIR CONDITIONING, BLEED')),
                ('category', models.CharField(choices=[('EICAS', 'EICAS Message'), ('FAULT', 'Fault Code'), ('SYSTEM', 'System'), ('SYNONYM', 'Synonym')], default='EICAS', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
