# Generated by Django 6.0.5 on 2026-06-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_dispatchkeyworddictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchreference',
            name='status_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
