# Generated by Django 6.0.5 on 2026-06-02 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0007_dispatchreference_status_message'),
        ('manuals', '0008_manualpackage_merged_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchreference',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuals.aircraft'),
        ),
        migrations.AlterField(
            model_name='dispatchreference',
            name='amm_chapter',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dispatchreference',
            name='amm_search_keyword',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dispatchreference',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dispatchreference',
            name='eicas_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dispatchreference',
            name='fault_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dispatchreference',
            name='fim_chapter',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dispatchreference',
            name='fim_search_keyword',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dispatchreference',
            name='mel_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dispatchreference',
            name='mel_search_keyword',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dispatchreference',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
