# Generated by Django 6.0.5 on 2026-06-02 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0008_alter_dispatchreference_aircraft_and_more'),
        ('manuals', '0008_manualpackage_merged_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='MelDispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('level', models.CharField(blank=True, default='', max_length=50)),
                ('condition', models.TextField(blank=True, default='')),
                ('mel_item', models.CharField(blank=True, default='', max_length=100)),
                ('adc', models.CharField(blank=True, default='', max_length=50)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mel_dispatch_items', to='manuals.aircraft')),
                ('manual_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mel_dispatch_items', to='manuals.manualfile')),
            ],
            options={
                'ordering': ['message', 'mel_item'],
            },
        ),
    ]
