# Generated by Django 6.0.5 on 2026-06-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0009_meldispatchitem'),
        ('manuals', '0008_manualpackage_merged_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meldispatchitem',
            options={'ordering': ['message', 'mel_item', 'page_number']},
        ),
        migrations.AddField(
            model_name='meldispatchitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meldispatchitem',
            name='level',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='meldispatchitem',
            name='mel_item',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='meldispatchitem',
            name='message',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='meldispatchitem',
            constraint=models.UniqueConstraint(fields=('aircraft', 'manual_file', 'message', 'page_number'), name='unique_mel_dispatch_item'),
        ),
    ]
