# Generated by Django 6.0.5 on 2026-06-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0010_alter_meldispatchitem_options_and_more'),
        ('manuals', '0008_manualpackage_merged_pdf'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='meldispatchitem',
            name='unique_mel_dispatch_item',
        ),
        migrations.AddConstraint(
            model_name='meldispatchitem',
            constraint=models.UniqueConstraint(fields=('aircraft', 'manual_file', 'message', 'mel_item', 'page_number'), name='unique_mel_dispatch_item'),
        ),
    ]
