# Generated by Django 6.0.5 on 2026-06-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0012_remove_meldispatchitem_unique_mel_dispatch_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchreference',
            name='amm_task_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dispatchreference',
            name='fim_task_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dispatchreference',
            name='mel_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
