# Generated by Django 6.0.5 on 2026-05-30 07:20

import django.db.models.deletion
import manuals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(choices=[('BOEING', 'Boeing'), ('AIRBUS', 'Airbus')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('airbus_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aircraft',
                'verbose_name_plural': 'Aircraft',
                'ordering': ['maker', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ManualFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_type', models.CharField(choices=[('AMM', 'AMM'), ('FIM', 'FIM'), ('IPC', 'IPC'), ('MEL', 'MEL'), ('CDL', 'CDL')], max_length=10)),
                ('file', models.FileField(upload_to='manuals/', validators=[manuals.models.validate_manual_file])),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuals', to='manuals.aircraft')),
            ],
            options={
                'verbose_name': 'Manual File',
                'verbose_name_plural': 'Manual Files',
                'ordering': ['aircraft', 'manual_type'],
            },
        ),
    ]
