# Generated by Django 6.0.5 on 2026-05-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={'ordering': ['maker', 'name']},
        ),
    ]
