# Generated by Django 6.0.5 on 2026-05-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0002_alter_aircraft_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='manualfile',
            unique_together={('aircraft', 'manual_type')},
        ),
    ]
