# Generated by Django 6.0.5 on 2026-05-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0003_alter_manualfile_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirbusManualLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('manual_type', models.CharField(choices=[('AMM', 'AMM'), ('FIM', 'FIM'), ('IPC', 'IPC'), ('MEL', 'MEL'), ('CDL', 'CDL'), ('OTHER', 'OTHER')], default='OTHER', max_length=10)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['manual_type', 'title'],
            },
        ),
    ]
