# Generated by Django 6.0.5 on 2026-05-30 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0004_airbusmanuallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_type', models.CharField(choices=[('AMM', 'AMM'), ('FIM', 'FIM'), ('IPC', 'IPC')], max_length=10)),
                ('zip_file', models.FileField(upload_to='manual_packages/')),
                ('extracted_path', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_packages', to='manuals.aircraft')),
            ],
            options={
                'ordering': ['aircraft', 'manual_type'],
                'unique_together': {('aircraft', 'manual_type')},
            },
        ),
        migrations.CreateModel(
            name='ManualChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('subtask', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('pdf_relative_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='manuals.manualpackage')),
            ],
            options={
                'ordering': ['task', 'subtask'],
            },
        ),
        migrations.CreateModel(
            name='ManualPDFPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='manuals.manualchapter')),
            ],
            options={
                'ordering': ['chapter', 'page_number'],
                'unique_together': {('chapter', 'page_number')},
            },
        ),
    ]
