# Generated by Django 6.0.5 on 2026-05-31 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0005_manualpackage_manualchapter_manualpdfpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualFilePDFPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True)),
                ('manual_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_pages', to='manuals.manualfile')),
            ],
            options={
                'ordering': ['manual_file', 'page_number'],
                'unique_together': {('manual_file', 'page_number')},
            },
        ),
    ]
