# Generated by Django 6.0.5 on 2026-05-31 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0006_manualfilepdfpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualIndexLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('PACKAGE', 'ZIP Package'), ('PDF', 'PDF File')], max_length=20)),
                ('manual_type', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('chapter_count', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manuals.aircraft')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
