# Generated by Django 6.0.5 on 2026-06-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manuals", "0006_manualfilepdfpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualpackage",
            name="merged_pdf",
            field=models.FileField(blank=True, null=True, upload_to="merged_manuals/"),
        ),
    ]
