# Generated by Django 6.0.5 on 2026-06-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0008_manualpackage_merged_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualfile',
            name='revision_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='manualpackage',
            name='revision_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
