# Generated by Django 6.0.5 on 2026-06-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0009_manualfile_revision_no_manualpackage_revision_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpackage',
            name='revision_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
