# Generated by Django 6.0.5 on 2026-06-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0010_manualpackage_revision_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualpackage',
            name='revision_date',
        ),
        migrations.AddField(
            model_name='manualpackage',
            name='revision_date_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
