# Generated by Django 6.0.5 on 2026-06-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0011_remove_manualpackage_revision_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualfile',
            name='revision_date_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
