# Generated by Django 6.0.5 on 2026-06-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0012_manualfile_revision_date_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='maker',
            field=models.CharField(choices=[('BOEING', 'Boeing'), ('AIRBUS', 'Airbus')], default='BOEING', max_length=20),
        ),
    ]
