# Generated by Django 6.0.5 on 2026-06-10 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manuals", "0013_alter_aircraft_maker"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airbusmanuallink",
            options={},
        ),
        migrations.AddField(
            model_name="airbusmanuallink",
            name="aircraft",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="airbus_links",
                to="manuals.aircraft",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="airbusmanuallink",
            unique_together={("aircraft", "manual_type")},
        ),
        migrations.AlterField(
            model_name="airbusmanuallink",
            name="manual_type",
            field=models.CharField(
                choices=[("AMM", "AMM"), ("FIM", "FIM"), ("IPC", "IPC")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="airbusmanuallink",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name="airbusmanuallink",
            name="created_at",
        ),
    ]
