# Generated by Django 6.0.5 on 2026-06-10 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0014_alter_airbusmanuallink_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airbusmanuallink',
            name='aircraft',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='airbus_links', to='manuals.aircraft'),
            preserve_default=False,
        ),
    ]
