# Generated by Django 6.0.5 on 2026-06-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0015_alter_airbusmanuallink_aircraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airbusmanuallink',
            name='manual_type',
            field=models.CharField(choices=[('AMM', 'AMM'), ('FIM', 'FIM'), ('IPC', 'IPC'), ('OTHER', 'OTHER')], max_length=10),
        ),
    ]
