# Generated by Django 6.0.5 on 2026-06-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0016_alter_airbusmanuallink_manual_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualpackage',
            name='merged_pdf',
        ),
    ]
