# Generated by Django 6.0.5 on 2026-06-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0017_remove_manualpackage_merged_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airbusmanuallink',
            name='manual_type',
            field=models.CharField(choices=[('AMM', 'AMM'), ('FIM', 'FIM'), ('IPC', 'IPC'), ('OTHER', 'Other PDF')], max_length=10),
        ),
        migrations.AlterField(
            model_name='manualfile',
            name='manual_type',
            field=models.CharField(choices=[('AMM', 'AMM'), ('FIM', 'FIM'), ('IPC', 'IPC'), ('MEL', 'MEL'), ('CDL', 'CDL'), ('OTHER', 'Other PDF')], max_length=10),
        ),
        migrations.AlterField(
            model_name='manualpackage',
            name='manual_type',
            field=models.CharField(choices=[('AMM', 'AMM'), ('FIM', 'FIM'), ('IPC', 'IPC'), ('OTHER', 'Other PDF')], max_length=10),
        ),
    ]
