# Generated by Django 6.0.5 on 2026-06-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0018_alter_airbusmanuallink_manual_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualfile',
            name='manual_type',
            field=models.CharField(choices=[('AMM', 'AMM'), ('FIM', 'FIM'), ('IPC', 'IPC'), ('MEL', 'MEL'), ('CDL', 'CDL'), ('OTHER', 'Other PDF'), ('BOARDING', '탑승 정비')], max_length=10),
        ),
    ]
