# Generated by Django 6.0.5 on 2026-06-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0019_alter_manualfile_manual_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airbusmanuallink',
            name='manual_type',
            field=models.CharField(choices=[('AMM', 'AMM'), ('FIM', 'FIM'), ('IPC', 'IPC'), ('OTHER', 'Other PDF'), ('BOARDING', '탑승 정비')], max_length=20),
        ),
        migrations.AlterField(
            model_name='manualfile',
            name='manual_type',
            field=models.CharField(choices=[('AMM', 'AMM'), ('FIM', 'FIM'), ('IPC', 'IPC'), ('MEL', 'MEL'), ('CDL', 'CDL'), ('OTHER', 'Other PDF'), ('BOARDING', '탑승 정비')], max_length=20),
        ),
        migrations.AlterField(
            model_name='manualpackage',
            name='manual_type',
            field=models.CharField(choices=[('AMM', 'AMM'), ('FIM', 'FIM'), ('IPC', 'IPC'), ('OTHER', 'Other PDF'), ('BOARDING', '탑승 정비')], max_length=20),
        ),
    ]
