# Generated by Django 6.0.5 on 2026-06-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0021_commonmanualcategory_commonmanualfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmanualfile',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='common_manuals/pdf/'),
        ),
    ]
