# Generated by Django 6.0.5 on 2026-06-24 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0022_commonmanualfile_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airbusmanuallink',
            name='manual_type',
            field=models.CharField(choices=[('AMM', 'AMM'), ('FIM', 'FIM'), ('IPC', 'IPC'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='manualfile',
            name='manual_type',
            field=models.CharField(choices=[('AMM', 'AMM'), ('FIM', 'FIM'), ('IPC', 'IPC'), ('MEL', 'MEL'), ('CDL', 'CDL'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='manualpackage',
            name='manual_type',
            field=models.CharField(choices=[('AMM', 'AMM'), ('FIM', 'FIM'), ('IPC', 'IPC'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='OtherManualCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_categories', to='manuals.aircraft')),
            ],
            options={
                'ordering': ['aircraft__name', 'name'],
                'unique_together': {('aircraft', 'name')},
            },
        ),
        migrations.CreateModel(
            name='OtherManualFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='manuals/other/')),
                ('description', models.TextField(blank=True)),
                ('revision_no', models.CharField(blank=True, max_length=50)),
                ('revision_date_text', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='manuals.othermanualcategory')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='OtherManualPDFPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True)),
                ('other_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='manuals.othermanualfile')),
            ],
            options={
                'ordering': ['other_file', 'page_number'],
                'unique_together': {('other_file', 'page_number')},
            },
        ),
    ]
