# Generated by Django 6.0.5 on 2026-06-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0023_alter_airbusmanuallink_manual_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='othermanualcategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='othermanualcategory',
            name='name',
            field=models.CharField(default='OTHER', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='othermanualcategory',
            constraint=models.UniqueConstraint(fields=('aircraft',), name='unique_other_folder_per_aircraft'),
        ),
    ]
