# Generated by Django 6.0.5 on 2026-06-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0024_alter_othermanualcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='othermanualfile',
            name='converted_pdf',
            field=models.FileField(blank=True, null=True, upload_to='manuals/other/converted/'),
        ),
    ]
